### ISSUE TITLE
Issue with thehuntison mod by Korz for Hollowknight

### ISSUE THREAD

**Issue by mememe69420** [Korzer420/TheHuntIsOn#5] opened 2024-11-20 14:07 UTC
hello, the mod thehuntison for hollowknight isnt working properly. it does load in to the game but when me and a friend try to attack each other when one of us is hunter and the other one is speedrunner we dont do any damage

**Comment by Korzer420** [comment] 2024-11-21 07:14
Hey, the mod itself has nothing to do with any PvP related action. The reason that this doesn't work for you is probably caused by a wrong setup from you on the mod HKMP. I suspect that either: You and your friend are on the same "team" in that mod (again the roles assigned by THIS mod have nothing to do with actual PvP stuff) or you nail damage is 0. I suspect the former. If you need help resolving this issue, I'd recommend checking out the HK modding or HKMP discord. But again, this is not an issue with the TheHuntIsOn mod.

**Closed by Korzer420** 2024-11-21 07:14 UTC
